---
{{- if .Values.ha.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "artemis.fullname" . }}-backup
spec:
  selector:
    matchLabels:
{{ include "artemis.labels.backup" . | indent 6 }}
  serviceName: {{ include "artemis.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
    {{- if .Values.metrics.enabled }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9404"
    {{- end }}
      labels:
{{ include "artemis.labels.backup" . | indent 8 }}
    spec:
{{ include "artemis.statefulset.spec" . | indent 6 }}
          {{- if .Values.ha.enabled }}
          - key: broker-ha-backup.xml
            path: broker-00.xml
          - key: ha-backup.xml
            path: ha-backup.xml
          - key: connectors.xml
            path: connectors.xml
          {{- else }}
          - key: broker.xml
            path: broker-00.xml
          {{- end }}
{{ include "artemis.statefulset.volumeclaim" . | indent 2 }}
{{- end }}
