apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "artemis.fullname" . }}
  labels:
{{ include "artemis.labels" . | indent 4 }}
data:
  broker.xml: |
    <?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <configuration xmlns="urn:activemq" xmlns:xi="http://www.w3.org/2001/XInclude">
      <core xmlns="urn:activemq:core">
        <acceptors>
          <acceptor name="netty">tcp://0.0.0.0:61617</acceptor>
        </acceptor>
       
        <connectors>
          <connector name="netty">tcp://0.0.0.0:61617</connector>
        </connectors>

        <broadcast-group name="jgroups-kube-ping">
          <jgroups-file>jgroups-kube-ping.xml</jgroups-file>
          <jgroups-channel>activemq_broadcast_channel</jgroups-channel>
          <broadcast-period>2000</broadcast-period>
          <connector-ref>netty</connector-ref>
        </broadcast-group>

        <discovery-groups>
          <discovery-group name="jgroups-kube-ping">
              <jgroups-file>jgroups-kube-ping.xml</jgroups-file>
              <jgroups-channel>activemq_broadcast_channel</jgroups-channel>
              <refresh-timeout>10000</refresh-timeout>
          </discovery-group>
        </discovery-groups>

        <xi:include href="addresses.xml"/>
        <xi:include href="address-settings.xml" />
      </core>
    </configuration>

  jgroups-kube-ping: |
    TODO

  addresses.xml: |
    <addresses xmlns="urn:activemq:core">
    {{- range .Values.addresses }}
      <address name="{{ required "name is mandatory for each address" .name }}">
      {{- if eq "queue" (default "queue" .type) }}
        <anycast>
        {{- if .queues }}
            {{- range .queues }}
              <queue name="{{ . }}" />
            {{- end }}
        {{- else }}
            <queue name="{{ .name }}" />
        {{- end }}
        </anycast>
      {{- else if eq "topic" .type }}
        <multicast />  
      {{- else }}
        {{- fail "invald address type. Can only be 'queue' or 'topic'"}}
      {{- end }}
      </address>
    {{- end }}
    </addresses>

  address-settings.xml: |
    <address-settings xmlns="urn:activemq:core">
    {{- range .Values.addressSettings }}
       <address-setting match="{{ required "match is mandatory for each addressSetting" .match }}">
       {{- range $key, $value := .settings }}
        <{{ $key }}>{{ $value }}</{{ $key }}>
       {{- end }}
       </address-setting>
    {{- end }}
    </address-settings>

 