apiVersion: v1
kind: Service
metadata:
  name: {{ include "artemis.fullname" . }}
  labels:
{{ include "artemis.labels" . | indent 4 }}
spec:
  clusterIP: None
  ports:
    - port: 61617
      targetPort: netty
      protocol: TCP
      name: netty
  selector:
    app.kubernetes.io/name: {{ include "artemis.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
