---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "artemis.fullname" . }}
spec:
  selector:
    matchLabels:
{{ include "artemis.labels" . | indent 6 }}
  serviceName: {{ include "artemis.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
    {{- if .Values.metrics.enabled }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9404"
    {{- end }}
      labels:
{{ include "artemis.labels" . | indent 8 }}
    spec:
      initContainers:
      - name: copy-broker-config
        image: bash:5
        command:
          - bash
        args:
          - -c
          - cp /tmp/config/*.{xml,xslt} /tmp/etc-override/
        volumeMounts:
        - name: config
          mountPath: /tmp/config
        - name: etc-override
          mountPath: /tmp/etc-override
      containers:
      - name: activemq-artemis 
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy}}
        ports:
        - containerPort: 61617
          name: netty
        - containerPort: 5672
          name: amq
        - containerPort: 61613
          name: stomp
        - containerPort: 1883
          name: mqtt
        - containerPort: 7800
          name: jgroups
        - containerPort: 8888
          name: kubeping
        {{- if .Values.metrics.enabled }}
        - containerPort: 9404
          name: prometheus
        {{- end }}
        env:
          - name: JAVA_OPTS
            value: {{ .Values.javaOpts }}    
          - name: ARTEMIS_USERNAME
            value: {{ .Values.auth.clientUser }}
          - name: ARTEMIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "artemis.fullname" . }}
                key: clientPassword
          - name: BROKER_CONFIG_CLUSTER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "artemis.fullname" . }}
                key: clusterPassword
          - name: ENABLE_JMX_EXPORTER
            value: {{ .Values.metrics.enabled | quote }}
        {{- if .Values.containerSecurityContext }}
        securityContext:
{{ toYaml .Values.containerSecurityContext | indent 10 }}
        {{- end }}
        volumeMounts:
        - name: data
          mountPath: /var/lib/artemis/data
        - name: etc-override
          mountPath: /var/lib/artemis/etc-override
        - name: jgroups
          mountPath: /var/lib/artemis/etc/jgroups
      serviceAccount: {{ include "artemis.fullname" . }}
      {{- if .Values.podSecurityContext }}
      securityContext:
{{ toYaml .Values.podSecurityContext | indent 8 }}
      {{- end }}
      volumes:
      - name: etc-override
        empty: {}
      - name: jgroups
        configMap:
          name: {{ include "artemis.fullname" . }}
          items:
          - key: jgroups-discovery.xml
            path: jgroups-discovery.xml
      - name: config
        configMap:
          name: {{ include "artemis.fullname" . }}
          items:
          {{- if .Values.ha.enabled }}
          - key: broker-ha-live.xml
            path: broker-00.xml
          - key: ha-live.xml
            path: ha-live.xml
          {{- else }}
          - key: broker.xml
            path: broker-00.xml
          {{- end }}
          - key: addresses.xml
            path: addresses.xml
          - key: address-settings.xml
            path: address-settings.xml
          - key: broadcast.xml
            path: broadcast.xml
          - key: clustering.xml
            path: clustering.xml
          - key: connectors.xml
            path: connectors.xml
          - key: discovery.xml
            path: discovery.xml
          - key: broker-00.xslt
            path: broker-00.xslt

     {{- if not .Values.persistence.enabled }}
      - name: data
        empty: {}
      {{- else }}
      volumeClaimTemplates:
      - metadata:
          name: data
        spec:
          accessModes:
{{ toYaml .Values.persistence.accessModes | indent 8 }}
          {{- if .Values.persistence.storageClassName }}
          storageClassName: {{ .Values.persistence.storageClassName }}
          {{- end }}
          resources:
            requests:
              storage: {{ .Values.persistence.storageSize }}
    {{- end }}
